### PR TITLE
add ubuntu 20.04 for owncloud-complete-10.5.0beta1

### PR DESCRIPTION
**Pull request by jnweiger**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Issues with the sernet repos: 

W: GPG error: https://download.owncloud.com/repositories/sernet/samba-4.8/ubuntu bionic Release: The following signatures were invalid: EXPKEYSIG D9921B1CF4428B1A Samba Support <Samba@SerNet.DE>
--

**Comment by micbar** [comment]
@DeepDiver1975 @jw we don't need the sernet repos anymore. They were just there to fix smbclient in 18.04

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @jw we don't need the sernet repos anymore. They were just there to fix smbclient in 18.04

ok - will take care ...

**Comment by DeepDiver1975** [comment]
16.04 and 18.04 have the same issue -  do we still need 16.04?

**Comment by DeepDiver1975** [comment]
Regarding the invalid key: we need to update our mirror of the sernet packages:

```
RUN curl -sSL https://download.owncloud.com/repositories/sernet/sernet.key | apt-key add - && \
  curl -sSL -o /etc/apt/sources.list.d/sernet.list http://download.owncloud.com/repositories/sernet/samba-4.8/ubuntu/dists/bionic/sernet-samba-4.8.list

**Comment by jnweiger** [comment]
The sernet key is
```
pub   dsa1024 2008-03-11 [SC] [expired: 2020-05-24]
      79750C3187AF92DDAC46086FD9921B1CF4428B1A
uid           Samba Support <Samba@SerNet.DE>
```

Who can extend the key? It looks like it is owned by sernet. 

As a temporary workaround, I suggesting to accept unauthenticated sernet packages for ubtunu-18.04 and ubuntu-16.04 builds. The 19.x and 20.04 targets do not have the sernet dependency.

**Pull request merged**
